version: '3.8'

networks:
  parking:

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=parking
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-p123456"]
      timeout: 20s
      retries: 10
    networks:
      - parking
  app:
    depends_on:
      # - db
      db:
        condition: service_healthy
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=parking
      - MYSQL_PORT=3306
    stdin_open: true
    tty: true
    networks:
      - parking
      
volumes: 
  db: